/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package user;

import connection.MyConnection;
import dao.ForgotpasswordDao;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author DISHANTH
 */
public class Forgotpassword extends javax.swing.JFrame {

    /**
     * Creates new form Forgotpassword
     */
    ForgotpasswordDao fg = new ForgotpasswordDao();

    Color notEdit = new Color(204, 204, 204);
    Color edit = new Color(255, 255, 255);

    public Forgotpassword() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void init() {
        PasswordBox.setBackground(notEdit);
        UserNameBox.setBackground(edit);
        PasswordBox.setEditable(false);
        btnSave.setEnabled(false);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InputPannel = new javax.swing.JPanel();
        CloseBtn = new javax.swing.JLabel();
        LoginTitle = new javax.swing.JLabel();
        UserNameBox = new javax.swing.JTextField();
        PasswordBox = new javax.swing.JPasswordField();
        EmailLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        InputPannel.setBackground(new java.awt.Color(237, 242, 244));
        InputPannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CloseBtn.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        CloseBtn.setForeground(new java.awt.Color(43, 45, 66));
        CloseBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CloseBtn.setText("X");
        CloseBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseBtnMouseClicked(evt);
            }
        });
        InputPannel.add(CloseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 27, -1));

        LoginTitle.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        LoginTitle.setForeground(new java.awt.Color(43, 45, 66));
        LoginTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginTitle.setText("Forgot Password");
        LoginTitle.setToolTipText("Login");
        InputPannel.add(LoginTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 338, -1));

        UserNameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameBoxActionPerformed(evt);
            }
        });
        InputPannel.add(UserNameBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 161, 264, 35));

        PasswordBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordBoxActionPerformed(evt);
            }
        });
        InputPannel.add(PasswordBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 246, 264, 35));

        EmailLabel.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        EmailLabel.setForeground(new java.awt.Color(43, 45, 66));
        EmailLabel.setText("Set new password");
        InputPannel.add(EmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 222, -1, -1));

        PasswordLabel.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(43, 45, 66));
        PasswordLabel.setText("Enter Email ID");
        InputPannel.add(PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 133, -1, -1));

        btnSave.setBackground(new java.awt.Color(43, 45, 66));
        btnSave.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        InputPannel.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 264, 35));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hide.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        InputPannel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 30, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/visible.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        InputPannel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        InputPannel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InputPannel, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InputPannel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseBtnMouseClicked

    private void UserNameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameBoxActionPerformed

    private void PasswordBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordBoxActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (isEmpty()) {
            String email = UserNameBox.getText();
            String pass = String.valueOf(PasswordBox.getPassword());
            fg.setPassword(email, pass);
            new Login().setVisible(true);
            this.dispose();

        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        PasswordBox.setEchoChar((char) 0);
        jLabel1.setVisible(false);
        jLabel2.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        PasswordBox.setEchoChar('*');
        jLabel1.setVisible(true);
        jLabel2.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    private boolean isEmpty() {
        if (String.valueOf(PasswordBox.getPassword()).isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the new password", "Warning", 2);
            return false;
        }
        return true;
    }

    private boolean emailValidation() {
        if (UserNameBox.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your email address", "Warning", 2);
            return false;
        }
        return true;
    }

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        if (emailValidation()) {
            if (fg.isEmailExist(UserNameBox.getText())) {
                UserNameBox.setBackground(notEdit);
                UserNameBox.setEditable(false);
                PasswordBox.setBackground(edit);
                PasswordBox.setEditable(true);
                btnSave.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forgotpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forgotpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forgotpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forgotpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forgotpassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CloseBtn;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JPanel InputPannel;
    private javax.swing.JLabel LoginTitle;
    private javax.swing.JPasswordField PasswordBox;
    private javax.swing.JLabel PasswordLabel;
    public static javax.swing.JTextField UserNameBox;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
